In [240]:
import pandas as pd
import numpy as np
import datetime
from scipy.spatial.distance import euclidean
from scipy.spatial import distance
from workalendar.europe import Italy
from astral import Astral
from tsfresh import extract_relevant_features

# Preparing the dataset.

In [161]:
w = pd.read_csv('../traffic/T.csv')
file = pd.read_csv('../traffic/Traffic_dataset_v0.1.csv', parse_dates=['DATETIME'], date_parser=lambda x: pd.to_datetime(x, format='%Y-%m-%d %H:%M'))
file.head()

,ID_SENSOR,DIRECTION,DATETIME,NUM_VEHICLES,SPEED_MEAN,SPEED_SD,EVENT,LON,LAT
0,1,A,2018-09-01 02:00:00,NaN,NaN,NaN,NO_EVENT,12.291754,41.800588
1,1,A,2018-09-01 02:15:00,NaN,NaN,NaN,NO_EVENT,12.291754,41.800588
2,1,A,2018-09-01 02:30:00,NaN,NaN,NaN,NO_EVENT,12.291754,41.800588
3,1,A,2018-09-01 02:45:00,NaN,NaN,NaN,NO_EVENT,12.291754,41.800588
4,1,A,2018-09-01 03:00:00,NaN,NaN,NaN,NO_EVENT,12.291754,41.800588

In [162]:
file_new = file.dropna(subset=['NUM_VEHICLES', 'SPEED_MEAN', 'SPEED_SD'], axis=0, thresh=2)
file_new = file_new.reset_index()

In [163]:
w.drop(['Unnamed: 0', 'Unnamed: 0.1'],axis=1, inplace=True)

In [164]:
file_final = pd.concat([file_new, w], axis=1)

In [165]:
file_final.head()

,index,ID_SENSOR,DIRECTION,DATETIME,NUM_VEHICLES,SPEED_MEAN,SPEED_SD,EVENT,LON,LAT,Temp,Humidity,Wind,Precipitation,Pressure
0,24,1,A,2018-09-01 08:00:00,504.0,99.3,17.19,NO_EVENT,12.291754,41.800588,24.69,0.69,5.04,rain,1014.98
1,25,1,A,2018-09-01 08:15:00,481.0,102.1,18.12,NO_EVENT,12.291754,41.800588,24.78,0.69,5.02,rain,1015.01
2,26,1,A,2018-09-01 08:30:00,617.0,99.2,17.91,NO_EVENT,12.291754,41.800588,24.86,0.69,5.07,rain,1015.03
3,27,1,A,2018-09-01 08:45:00,562.0,101.7,16.62,NO_EVENT,12.291754,41.800588,24.95,0.69,5.18,rain,1015.06
4,28,1,A,2018-09-01 09:00:00,521.0,99.7,17.06,NO_EVENT,12.291754,41.800588,25.03,0.69,5.35,rain,1015.09

In [166]:
file_final.drop(['index', 'Precipitation'], axis=1, inplace=True)
file_final = file_final.dropna(subset=['SPEED_SD'], axis=0)
file_final = file_final.reset_index()

In [167]:
file_final.DIRECTION = pd.get_dummies(file_final.DIRECTION, prefix = 'A', drop_first=True)

In [168]:
file_final['prev15'] = file_final.NUM_VEHICLES.diff()
file_final['prev30'] = file_final.NUM_VEHICLES.diff(periods=2)
file_final=file_final.drop(['index'], axis=1)
file_final.head()

,ID_SENSOR,DIRECTION,DATETIME,NUM_VEHICLES,SPEED_MEAN,SPEED_SD,EVENT,LON,LAT,Temp,Humidity,Wind,Pressure,prev15,prev30
0,1,0,2018-09-01 08:00:00,504.0,99.3,17.19,NO_EVENT,12.291754,41.800588,24.69,0.69,5.04,1014.98,NaN,NaN
1,1,0,2018-09-01 08:15:00,481.0,102.1,18.12,NO_EVENT,12.291754,41.800588,24.78,0.69,5.02,1015.01,-23.0,NaN
2,1,0,2018-09-01 08:30:00,617.0,99.2,17.91,NO_EVENT,12.291754,41.800588,24.86,0.69,5.07,1015.03,136.0,113.0
3,1,0,2018-09-01 08:45:00,562.0,101.7,16.62,NO_EVENT,12.291754,41.800588,24.95,0.69,5.18,1015.06,-55.0,81.0
4,1,0,2018-09-01 09:00:00,521.0,99.7,17.06,NO_EVENT,12.291754,41.800588,25.03,0.69,5.35,1015.09,-41.0,-96.0

In [169]:
Speed_ser = file_final['SPEED_MEAN'][:-1]

In [170]:
Speed_ser.name = 'Prev_Speed'

In [171]:
file_final = pd.concat([file_final[1:].reset_index(), Speed_ser], axis=1, names=[file_final.columns, 'prev_speed'])
file_final=file_final.drop(['index'], axis=1)
file_final.head()

,ID_SENSOR,DIRECTION,DATETIME,NUM_VEHICLES,SPEED_MEAN,SPEED_SD,EVENT,LON,LAT,Temp,Humidity,Wind,Pressure,prev15,prev30,Prev_Speed
0,1,0,2018-09-01 08:15:00,481.0,102.1,18.12,NO_EVENT,12.291754,41.800588,24.78,0.69,5.02,1015.01,-23.0,NaN,99.3
1,1,0,2018-09-01 08:30:00,617.0,99.2,17.91,NO_EVENT,12.291754,41.800588,24.86,0.69,5.07,1015.03,136.0,113.0,102.1
2,1,0,2018-09-01 08:45:00,562.0,101.7,16.62,NO_EVENT,12.291754,41.800588,24.95,0.69,5.18,1015.06,-55.0,81.0,99.2
3,1,0,2018-09-01 09:00:00,521.0,99.7,17.06,NO_EVENT,12.291754,41.800588,25.03,0.69,5.35,1015.09,-41.0,-96.0,101.7
4,1,0,2018-09-01 09:15:00,448.0,99.2,17.98,NO_EVENT,12.291754,41.800588,25.11,0.67,5.48,1015.09,-73.0,-114.0,99.7

In [172]:
cal = Italy()

In [173]:
file_final['DATETIME'][0].date()

datetime.date(2018, 9, 1)

In [174]:
feste = []
for i in file_final['DATETIME']:
    feste.append(int(cal.is_working_day(i.date())))

In [175]:
file_final['Working_Days'] = pd.Series(feste, name = 'Working_Days')

In [176]:
file_final.loc[file_final['Working_Days']==0]

,ID_SENSOR,DIRECTION,DATETIME,NUM_VEHICLES,SPEED_MEAN,SPEED_SD,EVENT,LON,LAT,Temp,Humidity,Wind,Pressure,prev15,prev30,Prev_Speed,Working_Days
0,1,0,2018-09-01 08:15:00,481.0,102.1,18.12,NO_EVENT,12.291754,41.800588,24.78,0.69,5.02,1015.01,-23.0,NaN,99.3,0
1,1,0,2018-09-01 08:30:00,617.0,99.2,17.91,NO_EVENT,12.291754,41.800588,24.86,0.69,5.07,1015.03,136.0,113.0,102.1,0
2,1,0,2018-09-01 08:45:00,562.0,101.7,16.62,NO_EVENT,12.291754,41.800588,24.95,0.69,5.18,1015.06,-55.0,81.0,99.2,0
3,1,0,2018-09-01 09:00:00,521.0,99.7,17.06,NO_EVENT,12.291754,41.800588,25.03,0.69,5.35,1015.09,-41.0,-96.0,101.7,0
4,1,0,2018-09-01 09:15:00,448.0,99.2,17.98,NO_EVENT,12.291754,41.800588,25.11,0.67,5.48,1015.09,-73.0,-114.0,99.7,0
5,1,0,2018-09-01 09:30:00,574.0,97.5,16.57,NO_EVENT,12.291754,41.800588,25.18,0.64,5.65,1015.09,126.0,53.0,99.2,0
6,1,0,2018-09-01 09:45:00,539.0,97.4,17.95,NO_EVENT,12.291754,41.800588,25.25,0.61,5.87,1015.08,-35.0,91.0,97.5,0
7,1,0,2018-09-01 10:00:00,525.0,96.7,18.54,NO_EVENT,12.291754,41.800588,25.32,0.59,6.12,1015.08,-14.0,-49.0,97.4,0
8,1,0,2018-09-01 10:15:00,506.0,97.5,17.60,NO_EVENT,12.291754,41.800588,25.21,0.59,5.81,1015.05,-19.0,-33.0,96.7,0
9,1,0,2018-09-01 10:30:00,679.0,94.9,17.91,NO_EVENT,12.291754,41.800588,25.10,0.60,5.51,1015.02,173.0,154.0,97.5,0
10,1,0,2018-09-01 10:45:00,695.0,91.9,16.65,NO_EVENT,12.291754,41.800588,24.99,0.61,5.22,1014.99,16.0,189.0,94.9,0
11,1,0,2018-09-01 11:00:00,569.0,94.4,18.35,NO_EVENT,12.291754,41.800588,24.88,0.61,4.95,1014.96,-126.0,-110.0,91.9,0
12,1,0,2018-09-01 11:15:00,517.0,97.4,19.50,NO_EVENT,12.291754,41.800588,25.13,0.61,4.89,1014.90,-52.0,-178.0,94.4,0
13,1,0,2018-09-01 11:30:00,726.0,94.5,17.77,NO_EVENT,12.291754,41.800588,25.38,0.60,4.83,1014.85,209.0,157.0,97.4,0
14,1,0,2018-09-01 11:45:00,647.0,96.0,18.87,NO_EVENT,12.291754,41.800588,25.63,0.60,4.79,1014.79,-79.0,130.0,94.5,0
15,1,0,2018-09-01 12:00:00,623.0,91.0,17.52,NO_EVENT,12.291754,41.800588,25.88,0.59,4.75,1014.74,-24.0,-103.0,96.0,0
16,1,0,2018-09-01 12:15:00,572.0,93.1,17.53,NO_EVENT,12.291754,41.800588,25.92,0.60,4.79,1014.67,-51.0,-75.0,91.0,0
17,1,0,2018-09-01 12:30:00,709.0,93.2,18.08,NO_EVENT,12.291754,41.800588,25.96,0.60,4.82,1014.60,137.0,86.0,93.1,0
18,1,0,2018-09-01 12:45:00,617.0,100.2,16.91,NO_EVENT,12.291754,41.800588,26.01,0.61,4.86,1014.53,-92.0,45.0,93.2,0
19,1,0,2018-09-01 13:00:00,573.0,96.6,19.48,NO_EVENT,12.291754,41.800588,26.04,0.61,4.90,1014.46,-44.0,-136.0,100.2,0
20,1,0,2018-09-01 13:15:00,494.0,98.5,19.23,NO_EVENT,12.291754,41.800588,26.14,0.60,4.84,1014.39,-79.0,-123.0,96.6,0
21,1,0,2018-09-01 13:30:00,580.0,96.9,17.99,NO_EVENT,12.291754,41.800588,26.24,0.59,4.78,1014.33,86.0,7.0,98.5,0
22,1,0,2018-09-01 13:45:00,557.0,95.5,18.66,NO_EVENT,12.291754,41.800588,26.34,0.58,4.72,1014.26,-23.0,63.0,96.9,0
23,1,0,2018-09-01 14:00:00,546.0,97.7,17.76,NO_EVENT,12.291754,41.800588,26.44,0.58,4.66,1014.20,-11.0,-34.0,95.5,0
24,1,0,2018-09-01 14:15:00,455.0,99.5,20.75,NO_EVENT,12.291754,41.800588,26.43,0.57,4.37,1014.15,-91.0,-102.0,97.7,0
25,1,0,2018-09-01 14:30:00,501.0,97.2,19.04,NO_EVENT,12.291754,41.800588,26.43,0.56,4.09,1014.10,46.0,-45.0,99.5,0
26,1,0,2018-09-01 14:45:00,523.0,98.0,20.25,NO_EVENT,12.291754,41.800588,26.42,0.55,3.81,1014.05,22.0,68.0,97.2,0
27,1,0,2018-09-01 15:00:00,408.0,96.4,20.79,NO_EVENT,12.291754,41.800588,26.41,0.55,3.55,1014.01,-115.0,-93.0,98.0,0
28,1,0,2018-09-01 15:15:00,399.0,100.4,20.29,NO_EVENT,12.291754,41.800588,26.17,0.57,3.61,1013.99,-9.0,-124.0,96.4,0
29,1,0,2018-09-01 15:30:00,174.0,98.7,17.56,NO_EVENT,12.291754,41.800588,25.93,0.60,3.69,1013.97,-225.0,-234.0,100.4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27714,4,1,2018-11-04 12:15:00,684.0,87.0,16.63,NO_EVENT,15.865158,38.364355,18.82,0.74,3.64,1016.69,66.0,72.0,85.6,0
27715,4,1,2018-11-04 12:30:00,646.0,85.6,17.17,NO_EVENT,15.865158,38.364355,19.22,0.72,3.80,1016.63,-38.0,28.0,87.0,0
27716,4,1,2018-11-04 12:45:00,670.0,85.9,15.82,NO_EVENT,15.865158,38.364355,19.61,0.70,3.97,1016.56,24.0,-14.0,85.6,0
27717,4,1,2018-11-04 13:00:00,619.0,86.5,16.33,NO_EVENT,15.865158,38.364355,20.01,0.68,4.14,1016.50,-51.0,-27.0,85.9,0
27718,4,1,2018-11-04 13:15:00,608.0,88.9,17.57,NO_EVENT,15.865158,38.364355,19.76,0.69,3.83,1016.44,-11.0,-62.0,86.5,0
27719,4,1,2018-11-04 13:30:00,605.0,86.4,17.00,NO_EVENT,15.865158,38.364355,19.51,0.71,3.59,1016.39,-3.0,-14.0,88.9,0
27720,4,1,2018-11-04 13:45:00,561.0,89.8,18.00,NO_EVENT,15.865158,38.364355,19.26,0.72,3.46,1016.34,-44.0,-47.0,86.4,0
27721,4,1,2018-11-04 14:00:00,594.0,86.5,16.61,NO_EVENT,15.865158,38.364355,19.00,0.73,3.44,1016.28,33.0,-11.0,89.8,0
27722,4,1,2018-11-04 14:15:00,649.0,87.1,16.97,NO_EVENT,15.865158,38.364355,19.11,0.72,2.88,1016.26,55.0,88.0,86.5,0
27723,4,1,2018-11-04 14:30:00,703.0,85.8,16.06,NO_EVENT,15.865158,38.364355,19.22,0.72,2.36,1016.23,54.0,109.0,87.1,0
27724,4,1,2018-11-04 14:45:00,672.0,85.5,17.57,NO_EVENT,15.865158,38.364355,19.32,0.71,1.91,1016.20,-31.0,23.0,85.8,0
27725,4,1,2018-11-04 15:00:00,616.0,84.3,18.82,NO_EVENT,15.865158,38.364355,19.43,0.71,1.60,1016.17,-56.0,-87.0,85.5,0
27726,4,1,2018-11-04 15:15:00,729.0,81.9,17.68,NO_EVENT,15.865158,38.364355,19.18,0.72,1.14,1016.18,113.0,57.0,84.3,0
27727,4,1,2018-11-04 15:30:00,723.0,83.6,16.54,NO_EVENT,15.865158,38.364355,18.93,0.73,0.71,1016.18,-6.0,107.0,81.9,0
27728,4,1,2018-11-04 15:45:00,639.0,85.6,17.33,NO_EVENT,15.865158,38.364355,18.68,0.74,0.46,1016.18,-84.0,-90.0,83.6,0
27729,4,1,2018-11-04 16:00:00,670.0,84.8,17.19,NO_EVENT,15.865158,38.364355,18.43,0.75,0.64,1016.19,31.0,-53.0,85.6,0
27730,4,1,2018-11-04 16:15:00,719.0,80.1,18.05,NO_EVENT,15.865158,38.364355,18.11,0.78,0.30,1016.23,49.0,80.0,84.8,0
27731,4,1,2018-11-04 16:30:00,797.0,81.1,16.47,NO_EVENT,15.865158,38.364355,17.79,0.80,0.34,1016.26,78.0,127.0,80.1,0
27732,4,1,2018-11-04 16:45:00,699.0,83.0,15.96,NO_EVENT,15.865158,38.364355,17.47,0.82,0.69,1016.30,-98.0,-20.0,81.1,0
27733,4,1,2018-11-04 17:00:00,830.0,80.2,16.27,NO_EVENT,15.865158,38.364355,17.15,0.84,1.09,1016.34,131.0,33.0,83.0,0
27734,4,1,2018-11-04 17:15:00,814.0,76.7,16.02,NO_EVENT,15.865158,38.364355,17.26,0.84,1.48,1016.40,-16.0,115.0,80.2,0
27735,4,1,2018-11-04 17:30:00,847.0,76.5,16.19,NO_EVENT,15.865158,38.364355,17.36,0.83,1.98,1016.46,33.0,17.0,76.7,0
27736,4,1,2018-11-04 17:45:00,808.0,75.6,18.41,NO_EVENT,15.865158,38.364355,17.47,0.83,2.53,1016.52,-39.0,-6.0,76.5,0
27737,4,1,2018-11-04 18:00:00,713.0,75.7,16.74,NO_EVENT,15.865158,38.364355,17.58,0.83,3.10,1016.58,-95.0,-134.0,75.6,0
27738,4,1,2018-11-04 18:15:00,726.0,78.0,16.54,NO_EVENT,15.865158,38.364355,17.37,0.84,2.56,1016.65,13.0,-82.0,75.7,0
27739,4,1,2018-11-04 18:30:00,714.0,75.9,15.99,NO_EVENT,15.865158,38.364355,17.15,0.85,2.14,1016.72,-12.0,1.0,78.0,0
27740,4,1,2018-11-04 18:45:00,728.0,76.2,16.27,NO_EVENT,15.865158,38.364355,16.94,0.86,1.94,1016.79,14.0,2.0,75.9,0
27741,4,1,2018-11-04 19:00:00,641.0,78.7,17.02,NO_EVENT,15.865158,38.364355,16.72,0.87,2.00,1016.86,-87.0,-73.0,76.2,0
27742,4,1,2018-11-04 19:15:00,664.0,79.2,17.33,NO_EVENT,15.865158,38.364355,16.83,0.87,2.15,1016.92,23.0,-64.0,78.7,0
27743,4,1,2018-11-04 19:30:00,532.0,76.4,16.21,NO_EVENT,15.865158,38.364355,16.94,0.87,2.45,1016.98,-132.0,-109.0,79.2,0

In [187]:
file_final.EVENT = pd.to_numeric(file_final.EVENT, errors='coerce')
file_final.EVENT.fillna(0, inplace=True)

In [188]:
file_final.head()

,ID_SENSOR,DIRECTION,DATETIME,NUM_VEHICLES,SPEED_MEAN,SPEED_SD,EVENT,LON,LAT,Temp,Humidity,Wind,Pressure,prev15,prev30,Prev_Speed,Working_Days
0,1,0,2018-09-01 08:15:00,481.0,102.1,18.12,0.0,12.291754,41.800588,24.78,0.69,5.02,1015.01,-23.0,NaN,99.3,0
1,1,0,2018-09-01 08:30:00,617.0,99.2,17.91,0.0,12.291754,41.800588,24.86,0.69,5.07,1015.03,136.0,113.0,102.1,0
2,1,0,2018-09-01 08:45:00,562.0,101.7,16.62,0.0,12.291754,41.800588,24.95,0.69,5.18,1015.06,-55.0,81.0,99.2,0
3,1,0,2018-09-01 09:00:00,521.0,99.7,17.06,0.0,12.291754,41.800588,25.03,0.69,5.35,1015.09,-41.0,-96.0,101.7,0
4,1,0,2018-09-01 09:15:00,448.0,99.2,17.98,0.0,12.291754,41.800588,25.11,0.67,5.48,1015.09,-73.0,-114.0,99.7,0

In [191]:
def make_harmonic_features(value, period=24):
    value *= 2 * np.pi / period 
    return np.cos(value), np.sin(value)

In [202]:
euclidean(make_harmonic_features(0), make_harmonic_features(23))

0.26105238444010403

In [206]:
make_harmonic_features(1)

(0.9659258262890683, 0.25881904510252074)

In [238]:
a = pd.Series(data=[make_harmonic_features(x.hour) for x in file_final.DATETIME])

In [237]:
file_final['Hour'] = pd.Series(data = a)
file_final.head()

,ID_SENSOR,DIRECTION,DATETIME,NUM_VEHICLES,SPEED_MEAN,SPEED_SD,EVENT,LON,LAT,Temp,Humidity,Wind,Pressure,prev15,prev30,Prev_Speed,Working_Days,Hour
0,1,0,2018-09-01 08:15:00,481.0,102.1,18.12,0.0,12.291754,41.800588,24.78,0.69,5.02,1015.01,-23.0,NaN,99.3,0,"(-0.4999999999999998, 0.8660254037844387)"
1,1,0,2018-09-01 08:30:00,617.0,99.2,17.91,0.0,12.291754,41.800588,24.86,0.69,5.07,1015.03,136.0,113.0,102.1,0,"(-0.4999999999999998, 0.8660254037844387)"
2,1,0,2018-09-01 08:45:00,562.0,101.7,16.62,0.0,12.291754,41.800588,24.95,0.69,5.18,1015.06,-55.0,81.0,99.2,0,"(-0.4999999999999998, 0.8660254037844387)"
3,1,0,2018-09-01 09:00:00,521.0,99.7,17.06,0.0,12.291754,41.800588,25.03,0.69,5.35,1015.09,-41.0,-96.0,101.7,0,"(-0.7071067811865475, 0.7071067811865476)"
4,1,0,2018-09-01 09:15:00,448.0,99.2,17.98,0.0,12.291754,41.800588,25.11,0.67,5.48,1015.09,-73.0,-114.0,99.7,0,"(-0.7071067811865475, 0.7071067811865476)"

In [239]:
a = Astral()

In [ ]:
a.

In [242]:
file_final.head()

,ID_SENSOR,DIRECTION,DATETIME,NUM_VEHICLES,SPEED_MEAN,SPEED_SD,EVENT,LON,LAT,Temp,Humidity,Wind,Pressure,prev15,prev30,Prev_Speed,Working_Days,Hour
0,1,0,2018-09-01 08:15:00,481.0,102.1,18.12,0.0,12.291754,41.800588,24.78,0.69,5.02,1015.01,-23.0,NaN,99.3,0,"(-0.4999999999999998, 0.8660254037844387)"
1,1,0,2018-09-01 08:30:00,617.0,99.2,17.91,0.0,12.291754,41.800588,24.86,0.69,5.07,1015.03,136.0,113.0,102.1,0,"(-0.4999999999999998, 0.8660254037844387)"
2,1,0,2018-09-01 08:45:00,562.0,101.7,16.62,0.0,12.291754,41.800588,24.95,0.69,5.18,1015.06,-55.0,81.0,99.2,0,"(-0.4999999999999998, 0.8660254037844387)"
3,1,0,2018-09-01 09:00:00,521.0,99.7,17.06,0.0,12.291754,41.800588,25.03,0.69,5.35,1015.09,-41.0,-96.0,101.7,0,"(-0.7071067811865475, 0.7071067811865476)"
4,1,0,2018-09-01 09:15:00,448.0,99.2,17.98,0.0,12.291754,41.800588,25.11,0.67,5.48,1015.09,-73.0,-114.0,99.7,0,"(-0.7071067811865475, 0.7071067811865476)"

In [245]:
y = file_final['SPEED_MEAN']
X = file_final.drop(['SPEED_MEAN', 'SPEED_SD', 'LON', 'LAT', 'Prev_Speed'], axis=1)
features_filtered_direct = extract_relevant_features(X[1:], y[1:],
                                                     column_id='DATETIME')

Feature Extraction:   0%|          | 0/20 [00:00<?, ?it/s]

ZeroDivisionError: float division by zero

In [244]:
X

,ID_SENSOR,DIRECTION,DATETIME,NUM_VEHICLES,EVENT,Temp,Humidity,Wind,Pressure,prev15,prev30,Working_Days,Hour
0,1,0,2018-09-01 08:15:00,481.0,0.0,24.78,0.69,5.02,1015.01,-23.0,NaN,0,"(-0.4999999999999998, 0.8660254037844387)"
1,1,0,2018-09-01 08:30:00,617.0,0.0,24.86,0.69,5.07,1015.03,136.0,113.0,0,"(-0.4999999999999998, 0.8660254037844387)"
2,1,0,2018-09-01 08:45:00,562.0,0.0,24.95,0.69,5.18,1015.06,-55.0,81.0,0,"(-0.4999999999999998, 0.8660254037844387)"
3,1,0,2018-09-01 09:00:00,521.0,0.0,25.03,0.69,5.35,1015.09,-41.0,-96.0,0,"(-0.7071067811865475, 0.7071067811865476)"
4,1,0,2018-09-01 09:15:00,448.0,0.0,25.11,0.67,5.48,1015.09,-73.0,-114.0,0,"(-0.7071067811865475, 0.7071067811865476)"
5,1,0,2018-09-01 09:30:00,574.0,0.0,25.18,0.64,5.65,1015.09,126.0,53.0,0,"(-0.7071067811865475, 0.7071067811865476)"
6,1,0,2018-09-01 09:45:00,539.0,0.0,25.25,0.61,5.87,1015.08,-35.0,91.0,0,"(-0.7071067811865475, 0.7071067811865476)"
7,1,0,2018-09-01 10:00:00,525.0,0.0,25.32,0.59,6.12,1015.08,-14.0,-49.0,0,"(-0.8660254037844385, 0.5000000000000003)"
8,1,0,2018-09-01 10:15:00,506.0,0.0,25.21,0.59,5.81,1015.05,-19.0,-33.0,0,"(-0.8660254037844385, 0.5000000000000003)"
9,1,0,2018-09-01 10:30:00,679.0,0.0,25.10,0.60,5.51,1015.02,173.0,154.0,0,"(-0.8660254037844385, 0.5000000000000003)"
10,1,0,2018-09-01 10:45:00,695.0,0.0,24.99,0.61,5.22,1014.99,16.0,189.0,0,"(-0.8660254037844385, 0.5000000000000003)"
11,1,0,2018-09-01 11:00:00,569.0,0.0,24.88,0.61,4.95,1014.96,-126.0,-110.0,0,"(-0.9659258262890682, 0.258819045102521)"
12,1,0,2018-09-01 11:15:00,517.0,0.0,25.13,0.61,4.89,1014.90,-52.0,-178.0,0,"(-0.9659258262890682, 0.258819045102521)"
13,1,0,2018-09-01 11:30:00,726.0,0.0,25.38,0.60,4.83,1014.85,209.0,157.0,0,"(-0.9659258262890682, 0.258819045102521)"
14,1,0,2018-09-01 11:45:00,647.0,0.0,25.63,0.60,4.79,1014.79,-79.0,130.0,0,"(-0.9659258262890682, 0.258819045102521)"
15,1,0,2018-09-01 12:00:00,623.0,0.0,25.88,0.59,4.75,1014.74,-24.0,-103.0,0,"(-1.0, 1.2246467991473532e-16)"
16,1,0,2018-09-01 12:15:00,572.0,0.0,25.92,0.60,4.79,1014.67,-51.0,-75.0,0,"(-1.0, 1.2246467991473532e-16)"
17,1,0,2018-09-01 12:30:00,709.0,0.0,25.96,0.60,4.82,1014.60,137.0,86.0,0,"(-1.0, 1.2246467991473532e-16)"
18,1,0,2018-09-01 12:45:00,617.0,0.0,26.01,0.61,4.86,1014.53,-92.0,45.0,0,"(-1.0, 1.2246467991473532e-16)"
19,1,0,2018-09-01 13:00:00,573.0,0.0,26.04,0.61,4.90,1014.46,-44.0,-136.0,0,"(-0.9659258262890684, -0.25881904510252035)"
20,1,0,2018-09-01 13:15:00,494.0,0.0,26.14,0.60,4.84,1014.39,-79.0,-123.0,0,"(-0.9659258262890684, -0.25881904510252035)"
21,1,0,2018-09-01 13:30:00,580.0,0.0,26.24,0.59,4.78,1014.33,86.0,7.0,0,"(-0.9659258262890684, -0.25881904510252035)"
22,1,0,2018-09-01 13:45:00,557.0,0.0,26.34,0.58,4.72,1014.26,-23.0,63.0,0,"(-0.9659258262890684, -0.25881904510252035)"
23,1,0,2018-09-01 14:00:00,546.0,0.0,26.44,0.58,4.66,1014.20,-11.0,-34.0,0,"(-0.8660254037844388, -0.4999999999999997)"
24,1,0,2018-09-01 14:15:00,455.0,0.0,26.43,0.57,4.37,1014.15,-91.0,-102.0,0,"(-0.8660254037844388, -0.4999999999999997)"
25,1,0,2018-09-01 14:30:00,501.0,0.0,26.43,0.56,4.09,1014.10,46.0,-45.0,0,"(-0.8660254037844388, -0.4999999999999997)"
26,1,0,2018-09-01 14:45:00,523.0,0.0,26.42,0.55,3.81,1014.05,22.0,68.0,0,"(-0.8660254037844388, -0.4999999999999997)"
27,1,0,2018-09-01 15:00:00,408.0,0.0,26.41,0.55,3.55,1014.01,-115.0,-93.0,0,"(-0.7071067811865479, -0.7071067811865471)"
28,1,0,2018-09-01 15:15:00,399.0,0.0,26.17,0.57,3.61,1013.99,-9.0,-124.0,0,"(-0.7071067811865479, -0.7071067811865471)"
29,1,0,2018-09-01 15:30:00,174.0,0.0,25.93,0.60,3.69,1013.97,-225.0,-234.0,0,"(-0.7071067811865479, -0.7071067811865471)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27809,4,1,2018-11-06 09:00:00,692.0,0.0,19.43,0.76,3.97,1017.21,27.0,-22.0,1,"(-0.7071067811865475, 0.7071067811865476)"
27810,4,1,2018-11-06 09:15:00,682.0,0.0,19.43,0.76,4.03,1017.21,-10.0,17.0,1,"(-0.7071067811865475, 0.7071067811865476)"
27811,4,1,2018-11-06 09:30:00,578.0,0.0,19.43,0.76,4.09,1017.20,-104.0,-114.0,1,"(-0.7071067811865475, 0.7071067811865476)"
27812,4,1,2018-11-06 09:45:00,642.0,0.0,19.43,0.76,4.15,1017.19,64.0,-40.0,1,"(-0.7071067811865475, 0.7071067811865476)"
27813,4,1,2018-11-06 10:00:00,531.0,0.0,19.43,0.76,4.22,1017.18,-111.0,-47.0,1,"(-0.8660254037844385, 0.5000000000000003)"
27814,4,1,2018-11-06 10:15:00,525.0,0.0,19.57,0.73,4.30,1017.15,-6.0,-117.0,1,"(-0.8660254037844385, 0.5000000000000003)"
27815,4,1,2018-11-06 10:30:00,578.0,0.0,19.72,0.71,4.37,1017.11,53.0,47.0,1,"(-0.8660254037844385, 0.5000000000000003)"
27816,4,1,2018-11-06 10:45:00,527.0,0.0,19.86,0.69,4.44,1017.07,-51.0,2.0,1,"(-0.8660254037844385, 0.5000000000000003)"
27817,4,1,2018-11-06 11:00:00,478.0,0.0,20.01,0.66,4.51,1017.03,-49.0,-100.0,1,"(-0.9659258262890682, 0.258819045102521)"
27818,4,1,2018-11-06 11:15:00,543.0,0.0,20.01,0.68,4.58,1016.97,65.0,16.0,1,"(-0.9659258262890682, 0.258819045102521)"
27819,4,1,2018-11-06 11:30:00,606.0,0.0,20.01,0.69,4.64,1016.92,63.0,128.0,1,"(-0.9659258262890682, 0.258819045102521)"
27820,4,1,2018-11-06 11:45:00,565.0,0.0,20.01,0.71,4.72,1016.86,-41.0,22.0,1,"(-0.9659258262890682, 0.258819045102521)"
27821,4,1,2018-11-06 12:00:00,562.0,0.0,20.01,0.72,4.79,1016.80,-3.0,-44.0,1,"(-1.0, 1.2246467991473532e-16)"
27822,4,1,2018-11-06 12:15:00,607.0,0.0,19.90,0.72,4.75,1016.74,45.0,42.0,1,"(-1.0, 1.2246467991473532e-16)"
27823,4,1,2018-11-06 12:30:00,566.0,0.0,19.79,0.72,4.73,1016.67,-41.0,4.0,1,"(-1.0, 1.2246467991473532e-16)"
27824,4,1,2018-11-06 12:45:00,596.0,0.0,19.68,0.72,4.71,1016.61,30.0,-11.0,1,"(-1.0, 1.2246467991473532e-16)"
27825,4,1,2018-11-06 13:00:00,639.0,0.0,19.58,0.72,4.71,1016.54,43.0,73.0,1,"(-0.9659258262890684, -0.25881904510252035)"
27826,4,1,2018-11-06 13:15:00,387.0,0.0,19.58,0.72,4.64,1016.49,-252.0,-209.0,1,"(-0.9659258262890684, -0.25881904510252035)"
27827,4,1,2018-11-06 13:30:00,650.0,0.0,19.58,0.71,4.58,1016.44,263.0,11.0,1,"(-0.9659258262890684, -0.25881904510252035)"
27828,4,1,2018-11-06 13:45:00,576.0,0.0,19.58,0.71,4.53,1016.38,-74.0,189.0,1,"(-0.9659258262890684, -0.25881904510252035)"
27829,4,1,2018-11-06 14:00:00,596.0,0.0,19.58,0.70,4.49,1016.33,20.0,-54.0,1,"(-0.8660254037844388, -0.4999999999999997)"
27830,4,1,2018-11-06 14:15:00,747.0,0.0,19.58,0.70,4.56,1016.30,151.0,171.0,1,"(-0.8660254037844388, -0.4999999999999997)"
27831,4,1,2018-11-06 14:30:00,638.0,0.0,19.58,0.69,4.63,1016.27,-109.0,42.0,1,"(-0.8660254037844388, -0.4999999999999997)"
27832,4,1,2018-11-06 14:45:00,637.0,0.0,19.58,0.69,4.69,1016.24,-1.0,-110.0,1,"(-0.8660254037844388, -0.4999999999999997)"
27833,4,1,2018-11-06 15:00:00,644.0,0.0,19.58,0.68,4.77,1016.22,7.0,6.0,1,"(-0.7071067811865479, -0.7071067811865471)"
27834,4,1,2018-11-06 15:15:00,737.0,0.0,19.44,0.69,3.44,1016.22,93.0,100.0,1,"(-0.7071067811865479, -0.7071067811865471)"
27835,4,1,2018-11-06 15:30:00,592.0,0.0,19.31,0.69,2.12,1016.22,-145.0,-52.0,1,"(-0.7071067811865479, -0.7071067811865471)"
27836,4,1,2018-11-06 15:45:00,576.0,0.0,19.18,0.69,0.82,1016.23,-16.0,-161.0,1,"(-0.7071067811865479, -0.7071067811865471)"
27837,4,1,2018-11-06 16:00:00,540.0,0.0,19.04,0.69,0.64,1016.23,-36.0,-52.0,1,"(-0.5000000000000004, -0.8660254037844384)"
27838,4,1,2018-11-06 16:15:00,240.0,0.0,18.57,0.71,0.45,1016.27,-300.0,-336.0,1,"(-0.5000000000000004, -0.8660254037844384)"

In [190]:
file_final.to_csv('../traffic/file_final.csv')